[package]
authors = ["Saverio Miroddi <saverio.pub2@gmail.com>"]
edition = "2018"
name = "snake-rust-wasm-progress"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
getrandom = {version = "0.2.2", features = ["js"]}
js-sys = "0.3.47"
rand = "0.8.3"
wasm-bindgen = "0.2.63"
